### ISSUE TITLE
[Epic] GCP 7.0

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-gcp#1183]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Tracking tasks for GCP 7.0

Upstream Announcement: https://github.com/hashicorp/terraform-provider-google/issues/15582

[Release planning doc](https://docs.google.com/document/d/1W6rfskg5S23zGPuy4q9goaLG-26hvuwe14opezsU-Yg/edit)

### Affected area/feature

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1244
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1179
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1187
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1189
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1248
- [ ] https://github.com/pulumi/home/issues/3135
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1243
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1245
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1246
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1247
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1249
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1250
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1251
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1275
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1273
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1274
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1259
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1314
```

**Comment by guineveresaenger** [comment]
https://github.com/pulumi/pulumi-gcp/pull/1238

**Comment by guineveresaenger** [comment]
Notes:
- Several of the integration tests have been skipped for years. 
    - I enabled one of them in https://github.com/pulumi/pulumi-gcp/pull/1238/commits/f4aa0a6128d159ad5e3dea643d3346adeb16a0fe.
    - I filed https://github.com/pulumi/pulumi-gcp/issues/1257 to decide what to do with the others. Recommendation here is to not block the release on re-enabling these tests.

**Comment by guineveresaenger** [comment]
Update 10/16

- https://github.com/pulumi/pulumi-gcp/issues/1244 has a working release branch
    - Needs less flaky Cloud Function tests - see [P1 issue](https://github.com/pulumi/pulumi-gcp/issues/1267)
    - Needs rename of Labels - see [this document](https://docs.google.com/document/d/1pZDKjs4xbKj-vvtxr5ETNB_fGWZ0m6uQErrLLWn4AFw/edit#heading=h.kz0qlzp5i6vk); will file an issue
        - Upstream implementation seems solid and usable by us, saving us pain
-  https://github.com/pulumi/pulumi-gcp/issues/1187 is done as part of upgrade branch and will close when we merge
- https://github.com/pulumi/pulumi-gcp/issues/1189 is done as part of upgrade branch and will close when we merge
- https://github.com/pulumi/pulumi-gcp/issues/1245 is relatively small; the real "new" thing on this release is default Labels
- https://github.com/pulumi/pulumi-gcp/issues/1247 - likewise we will have to explain Labels and update the config guide
- https://github.com/pulumi/pulumi-gcp/issues/1249 is passing tests on alpha
- https://github.com/pulumi/pulumi-gcp/issues/1250 is passing almost all tests except a diff on the new Labels field

My guess after (somewhat) verifying today that defaultLabels works as-is on our end is cautiously that we could have things ready by EOW.

We may not want to block on Cloud Function tests but that is assigned to a p1 currently. The upstream upgrade is technically unrelated here, so we can modernize that functionality via patch/minor release.

**Comment by mikhailshilkov** [comment]
GCP v7 has shipped, our docs, templates, and examples were all updated. Closing the epic as done, thank you all!
