### ISSUE TITLE
GCP 7.0 Blog post

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-gcp#1246]
Publish a GCP 7.0 focused blog post.
```[tasklist]
### Tasks
- [x] Gather provider stats
- [x] Create chart
- [x] Create meta image
- [x] Draft post available for review
- [ ] Publish post
```
