### ISSUE TITLE
[Epic] GCP 8.0

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#2290]
## Overview
Safely and swiftly deliver Pulumi's version of the upstream major GCP provider release.
Upstream Announcement: https://github.com/hashicorp/terraform-provider-google/issues/18300

## Key KPIs
1. Within 2 months, a majority of users have upgraded to the new major version with success and no regressions.
2. Maintainers can reference a standardized process for this kind of release in the future

## Key Stakeholders
@iwahbe @guineveresaenger @VenelinMartinov @mjeffryes 
@pulumi/docs - we will update examples and templates, and create a blog post
@pulumi/customer-engineering - we would love to identify beta testers and request feedback 🙏 

### Before the upstream release
- Prepare and thoroughly test a prerelease based on an upstream prerelease if at all possible
- Audit patches and create issues for any resulting work
### Once the upstream release is live
- The upgrade issue itself will be created automatically once the upstream release is published and should be added to this epic.
- Follow the [major version release playbook](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/Release%3A%20Major%20Version.md] to prepare the release branch.
- Add any patch removals/updates to the release branch as separate commits
- Fix any bugs discovered while testing the upgrade
- Add any necessary tests
### When ready to release
- Cut Release v8.0.0 of pulumi-gcp
- Communications: Blog post, Release Notes and Migration Guide
- Documentation and Resources: All examples and teaching materials are updated to use GCP v8.0.0
### Post Release
- Create/update Major Tier 1 Provider Release Handbook as resulting reference for the team
- Release Retrospective: what went well/what could have gone better

### References 📔

- [x] [Project View](https://github.com/orgs/pulumi/projects/179)
- [ ] PR/FAQ - See Blog Post and Release Notes issues, below
- [x] [Design Doc](https://docs.google.com/document/d/17jlUYGHvond8NhehHep7JAYRQRJEB7tTb7q8XuiPu3s/edit#heading=h.f5kycb4ul5ek)
- [ ] UX Designs n/a
- [x] Decision Log - [Friction Log placeholder doc](https://docs.google.com/document/d/1fhPoKL1RQzlQtkJekllKmsnqS5n6LEV7I7nv56vi-Ow/edit)

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/2318

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/2319

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/2326

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/1188

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/2348

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-gcp/issues/2357
