### ISSUE TITLE
GCP Bringup Tracking Issue

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-gcp#7]
This meta-issue tracks the paper cuts that I run into. I'll split them out into bugs once we stabilize this repo a little bit. I'll be editing this issue continuously as I go.

* [x] Get the provider building with `dep` so we can ingest it in this repo https://github.com/pulumi/terraform-provider-google/pull/2
* [ ] Getting authentication right is not straightforward and is going to require a lot of docs.
* [ ] Pulumi CLI is occasionally slow to shutdown whenever an error occurs (blocks for 30 seconds)
* [ ] Examples can't enable Services due to https://github.com/terraform-providers/terraform-provider-google/issues/1579
* [ ] https://github.com/pulumi/pulumi-terraform/issues/40 - exposing a compute instance to the Internet requires you to give an empty map to a certain property, which triggers this bug
